import mongoose from "mongoose";
import productModel from "./models/productModel.js"; // adjust path if necessary
import "dotenv/config";

// 20 supermarket products
const products = [
  {
    _type: "new_arrivals",
    name: "Premium Jasmine Rice 5kg",
    images: [],
    price: 12.99,
    discountedPercentage: 10,
    stock: 120,
    soldQuantity: 300,
    category: "Cooking Ingredients",
    brand: "Royal Jasmine",
    badge: true,
    isAvailable: true,
    offer: true,
    description:
      "High-quality jasmine rice with a soft, fragrant grain. Perfect for daily meals.",
    tags: ["Cooking Ingredients"],
    threshold: 10,
  },
  {
    _type: "new_arrivals",
    name: "Coca-Cola Zero Sugar 1.5L",
    images: [],
    price: 1.3,
    discountedPercentage: 0,
    stock: 150,
    soldQuantity: 430,
    category: "Beverages",
    brand: "Coca-Cola",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Coca-Cola Zero Sugar delivers the same classic taste without the sugar.",
    tags: ["Beverages"],
    threshold: 15,
  },
  {
    _type: "new_arrivals",
    name: "Aquafina Purified Water 500ml",
    images: [],
    price: 0.3,
    discountedPercentage: 0,
    stock: 300,
    soldQuantity: 1000,
    category: "Beverages",
    brand: "Aquafina",
    badge: false,
    isAvailable: true,
    offer: false,
    description: "Clean and refreshing purified water from Aquafina.",
    tags: ["Beverages"],
    threshold: 30,
  },
  {
    _type: "new_arrivals",
    name: "Hao Hao Instant Noodles - Shrimp Flavor (Box of 30)",
    images: [],
    price: 4.99,
    discountedPercentage: 8,
    stock: 90,
    soldQuantity: 350,
    category: "Cooking Ingredients",
    brand: "Acecook",
    badge: true,
    isAvailable: true,
    offer: true,
    description:
      "Popular instant noodles with a spicy shrimp flavor.",
    tags: ["Cooking Ingredients"],
    threshold: 10,
  },
  {
    _type: "new_arrivals",
    name: "Vinamilk Fresh Milk With Sugar (4-pack)",
    images: [],
    price: 2.5,
    discountedPercentage: 5,
    stock: 180,
    soldQuantity: 420,
    category: "Dairy & Eggs",
    brand: "Vinamilk",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Fresh Vietnamese milk enriched with natural sweetness.",
    tags: ["Dairy & Eggs"],
    threshold: 25,
  },
  {
    _type: "new_arrivals",
    name: "TH True Milk 1L",
    images: [],
    price: 1.2,
    discountedPercentage: 5,
    stock: 140,
    soldQuantity: 300,
    category: "Dairy & Eggs",
    brand: "TH True Milk",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "High-quality pasteurized milk with natural flavor.",
    tags: ["Dairy & Eggs"],
    threshold: 15,
  },
  {
    _type: "new_arrivals",
    name: "Lay’s Classic Potato Chips 107g",
    images: [],
    price: 1.4,
    discountedPercentage: 0,
    stock: 85,
    soldQuantity: 240,
    category: "Snacks & Fast foods",
    brand: "Lay’s",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Crispy classic potato chips with signature Lay’s flavor.",
    tags: ["Snacks & Fast foods"],
    threshold: 10,
  },
  {
    _type: "new_arrivals",
    name: "Oreo Vanilla Cookies 133g",
    images: [],
    price: 1.1,
    discountedPercentage: 3,
    stock: 120,
    soldQuantity: 350,
    category: "Snacks & Fast foods",
    brand: "Oreo",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Crunchy Oreo cookies with creamy vanilla filling.",
    tags: ["Snacks & Fast foods"],
    threshold: 20,
  },
  {
    _type: "new_arrivals",
    name: "Fresh Chicken Eggs (10 pcs)",
    images: [],
    price: 2.0,
    discountedPercentage: 0,
    stock: 160,
    soldQuantity: 500,
    category: "Dairy & Eggs",
    brand: "Local Farm",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Fresh farm-raised chicken eggs rich in nutrients.",
    tags: ["Dairy & Eggs"],
    threshold: 25,
  },
  {
    _type: "new_arrivals",
    name: "Pork Belly 500g",
    images: [],
    price: 3.99,
    discountedPercentage: 0,
    stock: 70,
    soldQuantity: 200,
    category: "Meat & Seafood",
    brand: "CP",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Fresh pork belly ideal for grilling, boiling, or stir-frying.",
    tags: ["Meat & Seafood"],
    threshold: 10,
  },
  {
    _type: "new_arrivals",
    name: "Chicken Breast Fillet 1kg",
    images: [],
    price: 4.5,
    discountedPercentage: 0,
    stock: 90,
    soldQuantity: 200,
    category: "Meat & Seafood",
    brand: "CP",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Lean chicken breast high in protein and perfect for healthy meals.",
    tags: ["Meat & Seafood"],
    threshold: 12,
  },
  {
    _type: "new_arrivals",
    name: "Fresh Green Mustard 500g",
    images: [],
    price: 0.8,
    discountedPercentage: 0,
    stock: 70,
    soldQuantity: 150,
    category: "Fresh Produce",
    brand: "Local Farm",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Crisp and fresh green mustard suitable for soups and stir-fry dishes.",
    tags: ["Fresh Produce"],
    threshold: 10,
  },
  {
    _type: "new_arrivals",
    name: "Vietnamese Cherry Tomatoes 1kg",
    images: [],
    price: 1.1,
    discountedPercentage: 0,
    stock: 90,
    soldQuantity: 300,
    category: "Fresh Produce",
    brand: "Da Lat Farm",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Fresh, juicy tomatoes sourced from Da Lat.",
    tags: ["Fresh Produce"],
    threshold: 15,
  },
  {
    _type: "new_arrivals",
    name: "Bananas 1kg",
    images: [],
    price: 0.9,
    discountedPercentage: 0,
    stock: 120,
    soldQuantity: 260,
    category: "Fresh Produce",
    brand: "Local Farm",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Sweet and ripe bananas packed with natural energy.",
    tags: ["Fresh Produce"],
    threshold: 20,
  },
  {
    _type: "new_arrivals",
    name: "New Zealand Apples 1kg",
    images: [],
    price: 3.5,
    discountedPercentage: 0,
    stock: 80,
    soldQuantity: 200,
    category: "Fresh Produce",
    brand: "New Zealand",
    badge: true,
    isAvailable: true,
    offer: true,
    description:
      "Crisp and naturally sweet apples imported from New Zealand.",
    tags: ["Fresh Produce"],
    threshold: 10,
  },
  {
    _type: "new_arrivals",
    name: "OMO Matic Liquid Detergent 3.7kg",
    images: [],
    price: 7.3,
    discountedPercentage: 10,
    stock: 60,
    soldQuantity: 150,
    category: "Household Supplies",
    brand: "OMO",
    badge: true,
    isAvailable: true,
    offer: true,
    description:
      "Powerful liquid detergent that removes tough stains easily.",
    tags: ["Household Supplies"],
    threshold: 8,
  },
  {
    _type: "new_arrivals",
    name: "Sunlight Dishwashing Liquid 1.5L",
    images: [],
    price: 1.5,
    discountedPercentage: 0,
    stock: 90,
    soldQuantity: 200,
    category: "Household Supplies",
    brand: "Sunlight",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Effective grease-cutting dishwashing liquid with lemon fragrance.",
    tags: ["Household Supplies"],
    threshold: 15,
  },
  {
    _type: "new_arrivals",
    name: "Head & Shoulders Shampoo 650ml",
    images: [],
    price: 5.8,
    discountedPercentage: 5,
    stock: 70,
    soldQuantity: 200,
    category: "Personal Care",
    brand: "Head & Shoulders",
    badge: false,
    isAvailable: true,
    offer: false,
    description:
      "Anti-dandruff shampoo providing freshness and scalp protection.",
    tags: ["Personal Care"],
    threshold: 12,
  },
];


// Insert function
const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    await productModel.insertMany(products);

    console.log("✅ 20 supermarket products inserted successfully!");
  } catch (err) {
    console.error("❌ Error inserting products:", err);
  } finally {
    await mongoose.disconnect();
    console.log("Disconnected from MongoDB");
    process.exit(0);
  }
};

seedProducts();
